name: Trigger auto deployment for mcp-autotask

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-autotask-AutoDeployTrigger-b9cc7bbb-d1d7-4667-9a2f-7f004e4d0a75.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPAUTOTASK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPAUTOTASK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPAUTOTASK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: nectaraiacr.azurecr.io
          registryUsername: ${{ secrets.MCPAUTOTASK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPAUTOTASK_REGISTRY_PASSWORD }}
          containerAppName: mcp-autotask
          resourceGroup: n8n-rg
          imageToBuild: nectaraiacr.azurecr.io/mcp-autotask:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


